### ISSUE TITLE
label shapes unsupported on mxnet 0.11

### ISSUE THREAD

**Issue by StOnEGiggity** [msracver/Deformable-ConvNets#105]
Hi, It seems new label shapes does not support type 'list', the message is:

> TypeError: Arguments need to be shapes(tuple), but 'label' is <type 'list'>

is there any plan to update the code for the newest vision or could point out suitable vision in README.
Thanks

**Comment by YuwenXiong** [comment]
It seems that you try to run deeplab code, there is a bug and should be fixed now. Please check the updated code.

**Comment by kevin8new** [comment]
I cloned the Deformable-ConvNets on 16th Dec, but the same problem is still exist.
I flowed the README exactly, is there anything wrong with my mxnet? How can I check the version of the mxnet and fix it ?
@YuwenXiong

**Comment by StOnEGiggity** [comment]
Hi, I remember the bug occurred due to updating MXNet version, maybe 0.11.0, they change 'label' to be type 'tuple', so maybe your MXNet version and code version are not matching.

**Comment by kevin8new** [comment]
So how can I fix this bug and run the Deeplab?
@StOnEGiggity

**Comment by StOnEGiggity** [comment]
first, git pull Deformable-ConvNets and get newest version;second, update your MXNet at least 0.11.I have tried v0.11 and v0.12. Both seem ok. Third, if you still have this bug, check type of your label, it's easy to change type in your code.
